### ISSUE TITLE
Promises support for DOM components

### ISSUE THREAD

**Issue by romandragan** [eigenmethod/mol#149] opened 2017-02-08 08:49 UTC
@nin-jin, does $mol have internal support of promises, when we use them for lazy loading DOM? For example, if we need to call `setTimeout` and return value from it? Can we use `$mol_defer`/`$mol_atom` for that?

**Comment by nin-jin** [comment] 2017-02-08 09:15
You can use this pattern for abstraction of asynchrony:

```
@ $mol_mem()
response( next? : string , force : $mol_atom_force ) {

    // do some async request
    setTimeout( ()=> {

        // force push data to property when you get data
        this.response( 'some response' , $mol_atom_force )

    } )

    // Notify about data waiting
    throw new $mol_atom_wait( 'Waits for timed out' )
}
```

In othr code you should this property in simple sync way:

```
@ $mol_mem()
users() {
    return JSON.parse( this.response() )
}
```

[More about $mol_mem](../tree/master/mem)
Real world example: [$mol_http_request](../blob/master/http/request/request.ts)

**Comment by romandragan** [comment] 2017-02-21 12:30
@nin-jin,

`$mol_mem_key` works in strange way.

How to reproduce:

1. Declare function that returns sign in component loaded after timeout:
```
@ $mol_mem()
Sign_in() {
    let component = this.fetch('$testapp_page_signin');
    // this object:
    console.log(new $testapp_page_signin());
    // is not equal to this:
    console.log(component);
    return component;
}
```

2. Declare `fetch` function:
```
@ $mol_mem_key()
fetch<T>(name : string, next? : T, force? : $mol_atom_force) : T {
    setTimeout(() => {
        this.fetch(name, new $testapp_page_signin(), $mol_atom_force);
    }, 3000);
    throw new $mol_atom_wait('Loading component...');
}
```

3. Now we see two console outputs with two objects, that not equals (but they were created in the same way):
- first - created directly in `Sign_in()` function
- second - created in `$mol_mem_key` function in the same way.

![Inspector screenshot](http://image.prntscr.com/image/0d41a50662f0422697ef90787e520be5.png)

As a result of this behavior we have error in rendering returned component.

I suppose, that something is going wrong when we force pass new value here:
```
this.fetch(name, new $testapp_page_signin(), $mol_atom_force)
```

Maybe $mol_mem logic "brokes" object value...

**Comment by nin-jin** [comment] 2017-02-21 14:03
1. It is normal. $mol_mem stores values in owner object in fields like property calls. First object was rendered, but second was not.

2. Dynamic js-modules loading not supported by design. We strive to minimal bundle size and instantly transitions between application panels. 

2. In noraml way, you should not to create components in async tasks. Recommended way is creating of components instantly, not conditional and by factories, created at view.tree.

```tree
sub / <= Sign_in $testapp_page_signin data <= data null
```

```ts
@ $mol_mem()
data( next? : any , force? : $mol_atom_force ) {
    setTimeout( () => {
        this.data( { hello : 'world' } , $mol_atom_force )
    } , 3000 )
    throw new $mol_atom_wait( 'Loading component...' )
}
```

That code produces this steps:

1. Sign_in rendered to user instantly.
2. Part of Sign_int requests for data and stops because data not loaded.
3. Part of Sign_in are marked as "waiting" for user automatically. Other user interface will be accessable.
4. After 3 seconds data will be arrived.
5. Part of Sign_in are rerendered normally with new data.

See this app with http throttling as example: http://mol.js.org/app/files/

**Comment by romandragan** [comment] 2017-02-22 06:08
@nin-jin, OK, i get you.

Now I have one another strange behavior. Component rendering function like this:

```
@ $mol_mem()
Sign_in() {
var result = this.fetch('$testapp_page_signin');
if (typeof result == 'function') {
	return new $webmasters_testapp_page_signin();
}
return new $webmasters_testapp_page_signin();
}
```

Works well. But when (after timeout) we want to re-render same object in the same way - it does not work. It renders just string `$webmasters_testapp.Root(0).Sign_in()` instead of whole component (like in first turn).

**Comment by nin-jin** [comment] 2017-02-22 10:28
Can you provide a full code?

**Comment by romandragan** [comment] 2017-02-22 10:30
@nin-jin, https://github.com/instrumentisto/mol-app-example/blob/webpack-integration/webmasters/testapp/testapp.view.ts#L79

**Comment by nin-jin** [comment] 2017-02-22 13:42
You load one bundle twice. Every run creates $mol_view class. Objects which are created by $mol_view from first load is not instance of $mol_view from second load. In our code we use conditions like ```if( view instanceof $mol_view ) ...```.

**Comment by romandragan** [comment] 2017-02-23 08:02
@nin-jin,

```
@ $mol_mem()
Sign_in() {
    var result = $webmasters_lazyloader.fetch<$webmasters_testapp_page_signin>('$webmasters_testapp_page_signin'); // returns just 'test' string
    if (typeof result == 'string') {
        let newView = new $webmasters_testapp_page_signin();
        console.log(newView instanceof $mol_view); // TRUE
        return newView;
    }
    let oldView = new $webmasters_testapp_page_signin();
    console.log(oldView instanceof $mol_view); // TRUE
    return oldView;
}
```

Here we see, that in both cases created object is instance of `$mol_view`. You mean that this is different $mol_view's? That's the problem?

**Comment by nin-jin** [comment] 2017-02-23 09:07
Owner component created by old $mol_view, child component created by new $mol_view. When owner renders children, he check sub component for instanceof old $mol_view getted from closure.

You can setup breakpoint [here](https://github.com/eigenmethod/mol/blob/master/view/view.ts#L14) to see $mol_view redeclaration. Or [hrere](https://github.com/eigenmethod/mol/blob/master/view/view.ts#L193) to see this problem.

To solve this problem, bundles must not contain same modules. MAM do not support this strategy of bundling.

**Comment by romandragan** [comment] 2017-02-27 08:15
Yes, you were right. Dividing components into separate JS bundles without redeclaring same modules solves the problem. Even, lazy loading is working using atoms and HTML imports.

**Comment by nin-jin** [comment] 2017-04-02 06:51
Can i close this issue as resolved or you want to request some improvements in $mol?

**Closed** 2018-03-17 07:47 UTC
Labels: discussion
